### ISSUE TITLE
CSS files

### ISSUE THREAD

**Issue by vuxor** [nlukic97/zadatak_2#1]
If you have your SASS files, there is no need to have also the compiled CSS files in source code. You can add them to gitignore and only leave SASS ones.

**Comment by nlukic97** [comment]
I have just tried to compile the SCSS files to CSS on upon deployment. 
I have not managed to do it successfully yet.

**Comment by nlukic97** [comment]
UPDATE: I have been trying to run "npm install && npm compile:sass-once" in my project, but it looks like I cannot to this:
https://vercel.com/support/articles/npm-run-start-not-working

So the only way seems to be to upload the static CSS compiled during development.
